### ISSUE TITLE
Не работает интеграция

### ISSUE THREAD

**Issue by itsib** [vakio-ru/vakio_atmosphere#3]
Беда беда. Датчик CO2 Vakio Atmosphere 1.0.4 не конектится к локальному брокеру, что я только с ним не делал. Я отправляю ему команды в топик vakio/system несколько раз работало выключение\включение дисплея, и все, перестало. Сама интеграция почему то постоянно сама переподписывается на все топики. 

![image](https://github.com/user-attachments/assets/e5df85b8-2c11-4cb4-8141-f31cb1a2aea3)

Судя по прочитанным сообщениям у вас всего один разработчик, и бедный Сергей не успевает. Может есть что то что мне поможет подключить этот датчик к брокеру локальному? Он у вас не нешевый, а работает ну пока так себе. Надеюсь что все исправится.

**Comment by Anti-Sh** [comment]
Добрый день, касаемо неудачного подключения устройства к брокеру - https://vakio.ru/garantie/
Свяжитесь со службой заботы компании удобным для вас способом, там вам должны помочь.
